### ISSUE TITLE
Clarification on hashing APIs?

### ISSUE THREAD

**Issue by Aethios** [Noctem/Monocle#101]
The UI for hashes is somewhat confusing. I'm using 2x 500 rpm API keys. I understand the total jumps back and forth between the two keys, but does the total show the rpm currently being used or the rpm remaining? What happens if the rpm limit has been reached and a worker needs to make a request? Does it go back to the old API or simply not make the request and wait? In either case, is there some kind of warning? I'm not covering my entire scan area and I don't have enough information to make adjustments.

**Comment by Noctem** [comment]
The reason I haven't officially added support for multiple keys is that pogo_async (and pgoapi) don't yet properly store the stats for all keys, only the most recently used one.

As for the UI:
```
Hashes: 173/500, refresh in 16
           ↑                ↑
  remaining/keysize  seconds until new period
```
If the key is exhausted: its code on the dot grid will show `H` and it will wait until the start of the next period to make its request. It never falls back to the .45 API if you have a key set.

**Comment by Aethios** [comment]
This is exactly the information I needed. Thank you.
