### ISSUE TITLE
Empty altitude response

### ISSUE THREAD

**Issue by baskettcase** [Noctem/Monocle#106]
Did something change with the altitude code? My scan.log file is full of 

[2017-02-17 09:44:06][ WARNING][spawns] Empty altitude response for (##.###,##.###), falling back to random.

.## added for privacy :)

**Comment by Noctem** [comment]
I just added logging instead of silently falling back to random. Did you set a Google API key in config that has the elevation API enabled?

**Comment by baskettcase** [comment]
Ah that's what happened, my google key wasn't correct apparently. I double checked and put in the code again.. I must have missed a digit or two the first time, but now Im not getting any of the messages. Thanks for the place to look :)
