### ISSUE TITLE
Need help with initial set up

### ISSUE THREAD

**Issue by krasatusya** [Noctem/Monocle#110]
Hello,
I followed set up instructions and set up twitter notifications, 
but after running scan.py I see the following output and no twitts are coming.

I even tried to set up  NOTIFY_RANKING = 10 to make sure there would be no problem to find a pokemons

Obviously, I missed something, Please help me to set up everything correctly.
Thanks

terminal output:
=======================================================
. .
X .
[W2: BENCHING]      

Monocle running for 0:04:51.756482
Known spawns: 1, unknown: 1, more: 0
4 workers, 6 threads, 4 coroutines
DB queue: 0, sightings cache: 0, mystery cache: 0

Seen per worker: min 0, max 0, med 0
Visits per worker: min 0, max 0, med 0
Visit delay: min 0.0, max 0.0, med 0.0
Speed: min 0.0, max 15.5, med 0.0
Extra accounts: 0, CAPTCHAs needed: 1

Pokemon found count (10s interval):
0 0 0 0 0 0 0 0 0 0

Visits: 0, per second: 0.00
Skipped: 0, unnecessary: 0

Workers without sightings so far:
0, 1, 2, 3

**Comment by stunnaspinz** [comment]
Your workers have not found any Pokémon yet. Since you just got it running I would let it run for at least 2 hours so that it can find spawn points. I usually let mine run at least 8 hours before even trying to get notifications

Workers without sightings so far:
0, 1, 2, 3

**Comment by krasatusya** [comment]
@stunnaspinz 
Thank you very much for your help, I will wait.

Thanks
