### ISSUE TITLE
No IVs found in encounter

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#111]
`[2017-02-17 09:13:46][   ERROR][worker-4] Missing Pokemon data in encounter response.
[2017-02-17 09:13:46][ WARNING][notifier] IVs are supposed to be considered but were not found.`

If I run an old instance of the map, it works fine. If I pull I get that error.

Already did:
pip install -r requirements.txt --upgrade
pip install -r optional-requirements.txt --upgrade

No idea what else to do.

**Comment by AvatarQAZ** [comment]
Seeing a similar issue in the log files (scan) starting just today.  Getting an error sometimes on some encounters.  I switched from encountering 'notify' to 'all' to see what I needed to do to optimize requests and noted this error.  Gonna let it run for a few hours then switch back to 'notify' and see if I get the same problem.

**Comment by Avatar690** [comment]
Still seeing the same issue since the build mentioned 9 days ago.  Have tried varying configurations but still see this error in the log files.

**Comment by manolomanila** [comment]
Same here. I am still running a previous build of the scanner since I didn't find a solution for this issue. I'll try having another look into it once I have more free time.

In case it helps, last thing I was looking into was pogo_async (now aipogo) because I always got an error whenever I tried upgrading it, and I had to manually remove it from the python folder and reinstall.

**Comment by Avatar690** [comment]
I haven't had any build errors I wasn't able to overcome on any package.  

If there is more reference to the encounter I could try to do a correlation between the encounter and the error to see if in fact it is throwing the exception/warning falsely or re-encountering to pull data.

**Comment by manolomanila** [comment]
Are you getting any encounter data? or none at all like me?

**Comment by Avatar690** [comment]
Not in front of a machine to tell you for certain.  In some cases I am seeing none.  Will know more later.  A lot of things have changed in the last 24 hours that require looking into.

**Comment by evenly-epic-mule** [comment]
I created https://github.com/Noctem/Monocle/pull/93 because of this issue
after that I've noticed that I get quite some `Failed encountering #[...]: 3`
but no idea what is causing them

**Comment by MiguelGallegoRO** [comment]
With your changes i got...

[2017-03-20 17:25:09][   ERROR][worker-0] Failed encountering #194: 2
[2017-03-20 17:25:09][   ERROR][worker-10] Failed encountering #167: 2
[2017-03-20 17:25:09][   ERROR][worker-20] Failed encountering #216: 2

What means the result number???

**Comment by MiguelGallegoRO** [comment]
responses = await self.call(request, action=2.25)

What means action=2.25, and where's the .call function?

**Comment by bikthor** [comment]
I'm having the same case making the changes mentioned above:
[2017-03-21 17:01:23][   ERROR][worker-20] Failed encountering #122: 2

I have observed that in the call function I always get an exception in this part of the code:
`try:
      self.update_inventory(delta['inventory_items'])
  except KeyError:
      self.log.warning('Error updating inventory')
      pass`

It seems like the request is sent but the response is messed up...

**Comment by bikthor** [comment]
I have tried to print the responses variable and this is the result every time:
`{'ENCOUNTER': {'status': 2}, 'GET_BUDDY_WALKED': {'success': True}, 'GET_HATCHED_EGGS': {'success': True}, 'CHECK_CHALLENGE': {'challenge_url': ' '}, 'GET_INVENTORY': {'inventory_delta': {'original_timestamp_ms': 1490140534841, 'new_timestamp_ms': 1490140537989}, 'success': True}, 'CHECK_AWARDED_BADGES': {'success': True}}`

It looks like everything but the encounters is being processed...

**Comment by evenly-epic-mule** [comment]
Status 2 means not found, that is strange - It would be good to see the request sent to the server in this case

**Comment by MiguelGallegoRO** [comment]
I found the error..., omfg...I can´t believe...I put the radar at Mar del Plata for a friend, then I configure all, **player data**, coordenates, etc, and when I go to the logs to see the encounters.. I don't found the encounter error, I go to the database...THE MOVES and IVS are there!!!

I only have 1 explanation..., mistakes in the **player data** at config.py, some friends had the same error and the copied the big part of my configuratión.
Anyway as evenly-epic-mule said seeing the request sent we would have find the mistake probably.
Tomorrow I'll change the player data and will close the issue if ivs and moves works.

**Comment by MiguelGallegoRO** [comment]
IVs and Moves still not working, when I put the other radar only had changed: AREA_NAME, PLAYER_LOCALE and created new database, this is strange because there is not player data or area name here:

 request = request.encounter(encounter_id=pokemon['encounter_id'],
                                    spawn_point_id=spawn_id,
                                    player_latitude=self.location[0],
                                    player_longitude=self.location[1])


How can I print the request sent to the server?

**Comment by MiguelGallegoRO** [comment]
I begin to think there is something in the code that makes monocle not working at some countries. 
I'm testing monocle at diferent countries(I'll keep testing and updating this thread):


Found IVs and moves:
France(Paris), China(Hong Kong), United States(Denver).

Didn't found IVs and moves(Failed encountering #pokemon_number : 2):
Portugal(Oporto), Spain(Vigo).





I get PLAYER_LOCAL from here:
https://countrycode.org/
https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx
https://www.timeanddate.com/time/zone/

**Comment by DavePlater** [comment]
Is it an issue with pokemon names in names.py not being defined for the locale in use?

**Comment by MiguelGallegoRO** [comment]
I only see conf.LANGUAGE at names.py, nothing about location

**Comment by MiguelGallegoRO** [comment]
#197

**Comment by Noctem** [comment]
Fixed.
