### ISSUE TITLE
Spread of workers?

### ISSUE THREAD

**Issue by kpkirsch** [Noctem/Monocle#112]
Workers seem to congregate. I know there are a good handful of spawn points at the lower half of the map but the workers never seem to move from a small area once running. Any help would be appreciated.
![screen shot 2017-02-19 at 10 17 07 am](https://cloud.githubusercontent.com/assets/25883406/23104083/9977a48e-f68c-11e6-9e0c-1091ab39c61f.png)
![screen shot 2017-02-19 at 10 18 29 am](https://cloud.githubusercontent.com/assets/25883406/23104089/c981d8fc-f68c-11e6-9ee9-d85f96caa0e3.png)

**Comment by manolomanila** [comment]
run `py scan.py --bootstrap` and let it run for a couple of hours!

**Comment by kpkirsch** [comment]
Thanks.

**Comment by atticusm** [comment]
Hi! Question. Do I need to specify --bootstrap after each launch or just on the first?

**Comment by manolomanila** [comment]
Monocle should autorun bootstrap the first time you launch it, if it doesn't have spawns. You may want to force bootstrap again if it didn't find all spawns, or if you are increasing the scanning area.

**Comment by atticusm** [comment]
Awesome! Thank you so much for for your support! I wish i could do this. It
seems really cool.
