### ISSUE TITLE
[PGOAPI ERROR] Only few with api error but still lv2

### ISSUE THREAD

**Issue by xLeevo** [Noctem/Monocle#114]
Hello,
i tested monocle now and it did very fine with a test of 7 accounts(2x3), i started another try but the workers told me that there is an pgoapierror.
All the accounts are now lv 2-3, but the 3 Which cause the error are "just" lv 2. I dont know why they are even 2 if there was the error from the start on, can you help me out maybe?
![ss 2017-02-19 at 08 13 01](https://cloud.githubusercontent.com/assets/25885719/23105474/231e8bc8-f6e0-11e6-8d22-aad6482397cd.png)

**Comment by Aethios** [comment]
I am also experiencing this error. I ran for weeks with 100 accounts with no problems, increased to 150 with no problems. When I increased to 200 accounts, now I am seeing anywhere from 15-30 accounts at a time throwing this error.

**Comment by joebobfrank** [comment]
Also getting this error, logs show:

Traceback (most recent call last):
  File "c:\Users\Michael\Monocle\monocle\worker.py", line 625, in visit
    return await self.visit_point(point, bootstrap=bootstrap)
  File "c:\Users\Michael\Monocle\monocle\worker.py", line 756, in visit_point
    raise ex.UnexpectedResponseException('Bad MapObjects response.')
pogo_async.exceptions.UnexpectedResponseException: Bad MapObjects response.
[2017-02-23 19:51:28][   ERROR][worker-1] UnexpectedResponseException
Traceback (most recent call last):
  File "c:\Users\Michael\Monocle\monocle\worker.py", line 742, in visit_point
    map_objects = responses['GET_MAP_OBJECTS']
KeyError: 'GET_MAP_OBJECTS'

**Comment by joebobfrank** [comment]
get_player = responses['GET_PLAYER'] also throws an ignored KeyError.

**Comment by joebobfrank** [comment]
RPC requests are failing with status_code 100

**Comment by joebobfrank** [comment]
This is fixed with latest commits.

**Comment by Noctem** [comment]
Closing since this has likely been fixed. Reopen it if it's not, and include what the actual error is (from your *scan.log*).
