### ISSUE TITLE
Why does the symbol S mean?

### ISSUE THREAD

**Issue by xLeevo** [Noctem/Monocle#115]
I got some S in my status dots in the grid, they wont continue, what does the S mean? cant fix it without any information :D

**Comment by manolomanila** [comment]
Switch. You might have run out of extra accounts because of captchas or empty scans.

**Comment by xLeevo** [comment]
Well yea, i have zero extra accounts because i used a 5x5 grid with 25 accounts. if ill have 30 accounts so i got 5 extra accounts, i cant be sure that all are on level 2 after 16-20 spins can i?
