### ISSUE TITLE
ImportError: cannot import name 'close_sessions'

### ISSUE THREAD

**Issue by vlacorte** [Noctem/Monocle#117]
Updated to the last commit, tried running scan.py and got this error.

Complete trace mentions `from pogo_async import close_sessions`, but the module is not there. (Reverting to old `from pogo_async.session import Session` and performing a `Session.close()` solves it, so probably just a name conflict).

**Comment by daveyfong** [comment]
`pip3 install --ignore-installed git+https://github.com/Noctem/pgoapi.git@async#egg=pogo_async`

**Comment by vlacorte** [comment]
@daveyfong it worked, thank you! I'm pretty sure I performed `pip3 install -r requirements.txt` thinking it would perform similar to the command you posted.
