### ISSUE TITLE
Unable to import pycairo

### ISSUE THREAD

**Issue by therealphaTT** [Noctem/Monocle#118]
Windows 10, Python 3.6, scanning is working otherwise. I want to use Cairo to tweet images. I have tried multiple methods of installing pycairo.

First, tried to install from monocle folder. 
> could not find version that satisfies requirement pycairo (from version: ) no matching distribution for pycairo"

Then, tried to download from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo and using `pip install pycairo-1.10.0-cp36-cp36m-win_amd64.whl`
Gives error: 
>  Could not find a version that satisfies the requirement pycairo-1.10.0-cp36-cp36m-win_amd64 (from versions: )
> No matching distribution found for pycairo-1.10.0-cp36-cp36m-win_amd64

So, i used winRAR to extract the package and move to C:\Program Files (x86)\Python36-32\Lib\site-packages\cairo and then used `easy_install.py ` to install the module manually.

> Searching for pycairo
> Reading https://pypi.python.org/simple/pycairo/
> Best match: pycairo 1.10.0
> Adding pycairo 1.10.0 to easy-install.pth file
> 
> Using c:\program files (x86)\python36-32\lib\site-packages
> Processing dependencies for pycairo
> Finished processing dependencies for pycairo

So then, running `pip install pycairo` gives this:
> Requirement already satisfied: pycairo in c:\program files (x86)\python36-32\lib\site-packages

However, then running scan.py gives this:

> Traceback (most recent call last):
>   File "D:\Pokemon Go Tools\Monocle Scanner\monocle\notification.py", line 64, in <module>
>     import cairo
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\cairo\__init__.py", line 19, in <module>
>     from ._cairo import *
> ModuleNotFoundError: No module named 'cairo._cairo'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "scan.py", line 126, in <module>
>     from monocle.worker import Worker
>   File "D:\Pokemon Go Tools\Monocle Scanner\monocle\worker.py", line 25, in <module>
>     from .notification import Notifier
>   File "D:\Pokemon Go Tools\Monocle Scanner\monocle\notification.py", line 66, in <module>
>     raise ImportError('You enabled TWEET_IMAGES but Cairo could not be imported.') from e
> ImportError: You enabled TWEET_IMAGES but Cairo could not be imported.]

Any help would be appreciated, love the scanner so far.

**Comment by cgohlke** [comment]
`pycairo-1.10.0-cp36-cp36m-win_`**`amd64`**`.whl` is for 64-bit Python. Your are using 32-bit Python `C:\Program Files (x86)\Python36-`**`32`**

**Comment by therealphaTT** [comment]
Sorry, I forgot to mention that I tried every version available on the website from 27 all the way to 36, both 64 and 32 bit. Every .whl gives the same error when trying to install. I just did a completely fresh install of 3.6 and got rid of all old Python versions. 
Get Outlook for iOS




On Mon, Feb 20, 2017 at 3:02 PM -0500, "Christoph Gohlke" <notifications@github.com> wrote:












pycairo-1.10.0-cp36-cp36m-win_amd64.whl is for 64-bit Python. Your are using 32-bit Python C:\Program Files (x86)\Python36-32

**Comment by therealphaTT** [comment]
I ended up doing the manual process again with a new 32 .whl package and that worked. I must have not used the `easy_install` method with all of the packages like I previously had thought. Thank you.

**Comment by therealphaTT** [comment]
However, now it seems that pycairo is installed but not functioning. scan.py runs fine but my tweets do not contain images.

**Comment by stunnaspinz** [comment]
@therealphaTT make sure that you have images for each pokemon (named as 1.png 2.png 3.png etc.etc) in the folder "\static\monocle-icons\original-icons" This is the folder that is used for tweet images.

**Comment by therealphaTT** [comment]
@stunnaspinz That did it, thank you very much. Is there documentation for this I'm not paying attention to?

**Comment by stunnaspinz** [comment]
There is a wiki that I have looked at a few times (linked in this git) but not specifically related to certain things.. Somethings you have to see in the log file in the root monocle directory.
