### ISSUE TITLE
Reporting 100% Pokemon

### ISSUE THREAD

**Issue by AvatarQAZ** [Noctem/Monocle#120]
I just want to make sure I understand the logic:

If I set IGNORE_RARITY = True and set the INITIAL and MINIMUM_SCORE = 1, that should report all 100% Pokemon.  

Currently using NOTIFY_RANKING (will have to bump that up to 255 now) with ALWAYS_NOTIFY and TRASH.  There wouldn't be any conflicts?  Thanks!

**Comment by thordurk91** [comment]
encounter = 'all' is also needed. but looks like it should work, Just make sure you remake your ranking pickle, i.e. delete it and have it be re-generated.

**Comment by AvatarQAZ** [comment]
Confirmed.

encounter=all
ignore_rarity = 1
minimum_score = 1
initial_score = 1
