### ISSUE TITLE
How to remove previously added accounts?

### ISSUE THREAD

**Issue by vlacorte** [Noctem/Monocle#123]
Changing config.py does not remove previously added accounts since they seem to be stored on pickles. Is there a way to unload/refresh `accounts.pickle`?

**Comment by stunnaspinz** [comment]
accounts are all managed in the config.py file. If you want to add or remove accounts. Stop the scanning process remove and or add accounts to the list (pay attention to formatting), and restart the scanning.

**Comment by vlacorte** [comment]
@stunnaspinz sorry, hit enter before providing more info.

**Comment by stunnaspinz** [comment]
Ahhh I see @vlacorte .. I have been deleting the account.pickle file since its not a directly editable file.

**Comment by vlacorte** [comment]
It seems that data is only dumped to a pickle file (as in `monocle/utils.py, method `load_accounts`).

@Stunnaspins precisely! I'll simply remove accounts.pickle and let the program create it again when performing a scan.
