### ISSUE TITLE
Map to WAN

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#124]
How can I open the map to WAN? I think I've managed to open a port, but I have no idea of how I should configure the scanner to share the data to that port. Anything related to proxies in the config file?

**Comment by n30nl1ght** [comment]
You can start the scan.py normal.

The web.py must start with your port and your IP (ip of the computer or Server)

Example:
IP of PC/Server -> 192.168.1.10
Port -> 5000
python3 web.py -H 192.168.1.10 -P 5000

If you only use the port 5000, you do not have to specify this at start. Standart is the 5000.
Now you still have the port 5000 in the router to your PC / server forward.

Now you can access the map with your public IP and the port

**Comment by manolomanila** [comment]
Thank you! but I seem to be missing something;

```
192.168.1.145 - - [22/Feb/2017 09:14:49] "GET / HTTP/1.1" 200 -
192.168.1.145 - - [22/Feb/2017 09:14:49] "GET /scan_coords HTTP/1.1" 200 -
192.168.1.145 - - [22/Feb/2017 09:14:49] "GET /workers_data HTTP/1.1" 200 -
192.168.1.145 - - [22/Feb/2017 09:14:49] "GET /data?last_id=0 HTTP/1.1" 200 -
```

**Comment by stunnaspinz** [comment]
Logs look good to me. Open the address in a browser http://192.168.1.145/

**Comment by manolomanila** [comment]
Thanks for the answer. The map loads, but doesn't show Pokémon. With the default IP I was getting a more extent log without the `"GET /data?last_id=0 HTTP/1.1" 200`

**Comment by thordurk91** [comment]
Pokemon are only displayed if they have a known TTH. Got known spawns?

**Comment by manolomanila** [comment]
Yes, web.py works fine with the default IP; I can see spawns, Pokémon and all. With my IP it shows spawns, workers and the scanning area, but no Pokémon.

**Comment by manolomanila** [comment]
Downloaded Google Chrome and it works fine. Don't know why, but it doesn't in Safary on IOS or Chrome in my desktop PC.
