### ISSUE TITLE
Is Unown shown in Monacle?

### ISSUE THREAD

**Issue by baskettcase** [Noctem/Monocle#125]
since Unown has 26 different possibilities, Im curious whether Unown returns 201 when scanning, or if it returns a string 201A 201B, etc? And does Monocle support storing and displaying Unown?

**Comment by AvatarQAZ** [comment]
Short answer, yes.  My scanner detected one Unown.  I dont know what specific Unown it was but it did find one.  Monocle returned 201 and it is available in my reports section.

**Comment by thordurk91** [comment]
https://twitter.com/pokekort/status/834209957134344192

Yes.

**Comment by baskettcase** [comment]
Thank you guys, I appreciate the info! :)
