### ISSUE TITLE
2captcha not receiving captcha requests...

### ISSUE THREAD

**Issue by Aethios** [Noctem/Monocle#128]
I have a 2captcha key in the config. I know the key and account work because I've been using them both with another script to mass generate accounts. For some reason when I get a captcha on one of my workers, it just shelves the worker and doesn't send the captcha request to 2captcha.

**Comment by evenly-epic-mule** [comment]
I've had 7 Captchas today, and all where solved

have you checked your scan.log for error messages?

**Comment by stunnaspinz** [comment]
Also in the 2captcha control panel ensure that you have not enabled IP address restrictions or if you are using it make sure that the correct IP address is listed as allowed.

**Comment by Aethios** [comment]
It says it has solved 20 captchas today, but there is consistently 1 account that has a pending captcha. Does it simply not solve the captcha until it needs that account for rotation?

**Comment by stunnaspinz** [comment]
from my experience, it should solve the captchas as soon as they are encountered. if there is an error it will rest the account until it is needed for the rotation once again.  Have you tried to check the logs to see which account it is and then manually login via pogo app on phone and see if it truly needs a captcha and then solve it that way?

**Comment by Aethios** [comment]
I've been using the solve_captchas.py script to pop them up in Chrome and solve them, which acts as a temporary solution, but over time eventually another one will pop up and not get solved. I'm not sure if it's the same account. The logs are a tangled mess of thousands of exceptions of various kinds, sometimes creating exceptions of their own and flooding the log until it's unreadable. As long as it's not affecting the scanner I tend to ignore them.

[ERROR][eventloop] A wild exception appeared!
[ERROR][eventloop] {'message': 'Fatal error on SSL transport', 'exception': RuntimeError('handshake in progress or completed',), 'transport': <TCPTRansport closed=True reading=False (a bunch of gibberish numbers here)>, 'protocol': <asyncio.sslproto.SSLProtocol object at (a bunch of gibberish numbers again but not the same numbers as before)>}

**Comment by stunnaspinz** [comment]
(Side note) when I was manually solving captchas, I dont recall the accounts being placed back into the rotation. I switched over to using 2captcha and have not had any issues of accounts failing captcha at all.)

In the log file you should find which account specifically has caught the captcha.. 

[2017-02-20 20:35:49][ WARNING][worker-50] (Account_Name) has encountered a CAPTCHA, trying to solve
You should also see if there was an error or if it was solved correctly.
[2017-02-20 20:37:39][ WARNING][worker-50] Successfully solved CAPTCHA

**Comment by Aethios** [comment]
It tells me which account caught the captcha when I solve them manually, so I was able to confirm that it is NOT the same account each time. The account that caught it this time is one that I only created yesterday.

**Comment by Noctem** [comment]
As of d36cd066fd7b9f370c18bce9f8964c02058fee02, when using 2Captcha, it will take an account from the CAPTCHA queue (if there are any) when swapping so it should empty itself out. That behavior can be disabled with `FAVOR_CAPTCHA = False`.

**Comment by Aethios** [comment]
I haven't had any trouble with this in several days so I think it's safe to say this was successfully fixed.
