### ISSUE TITLE
How do I mark spawn point as super important?

### ISSUE THREAD

**Issue by bswan** [Noctem/Monocle#130]
Ok, I have one spawn point that have 1H spawn schedule and spawned 15 Houndours before migration(none of them spawned elsewhere). So, I want somehow mark it as super important, to make bots visit it ASAP after it respawns pokemon. Is it possible now, or you can implement that?

**Comment by therealphaTT** [comment]
I am no expert, but I assume that as long as you don't see any skipped or
unnecessary spawns during scans that it will visit it within 90 seconds of
the spawn point becoming active.

**Comment by AvatarQAZ** [comment]
Correct @therealphaTT.  Depends on the value of your GIVE_UP_KNOWN.  If Monocle can't find a worker after the value of that variable (in seconds) it will give up and move to the next spawn.  If you aren't seeing any skipped spawns then you will always be hitting that spawn WITHIN the value of GIVE_UP_KNOWN.

**Comment by bswan** [comment]
Ah, ok, so "have enough workers" the only answer... Ok

**Comment by Noctem** [comment]
Yes, there is currently no prioritization of spawn points.
