### ISSUE TITLE
TWEET IMAGES template?

### ISSUE THREAD

**Issue by therealphaTT** [Noctem/Monocle#134]
Hey all, 

I have been trying to get TWEET IMAGES to work properly. Here is what it looks like currently:
[link](https://twitter.com/GroveCityPKMN/status/834871430982545408)

I used the background from a PokemonGO asset repo, and resized it first to same size, 16x9 ratio. Then to 256x144. Model sizes are 120x120. I'm just guessing here. Is there any documentation I can look at or does anyone have the perfect sizes / ratios for the TWEET IMAGES command?
So it looks like [this.](https://twitter.com/SLCPokemon)

And does anyone know where to find Gen II models from GO? Spent some time on google and git and couldn't find anything to match SLCPokemon's models.

**Comment by stunnaspinz** [comment]
I have mine working perfectly.. Background image size is 400 x 240 (I used my own bg images for day and night). My Pokemon image files are 215 x 215. You can see the product live at [here](https://twitter.com/HendersonPkmon)

**Comment by stunnaspinz** [comment]
As for where the images were obtained. I downloaded each one from the pokedex at pokemon.com (I downloaded all 1st and 2nd gen images from them and saved them into the monocle\static\monocle-icons\original-icons directory.

**Comment by therealphaTT** [comment]
@stunnaspinz thanks, working great now.
