### ISSUE TITLE
Multiple Telegram notifications for the same Pokemon

### ISSUE THREAD

**Issue by skateskate** [Noctem/Monocle#144]
Hello,
as the title says, I've got a problem with Telegram notifications: in fact I usually receive two/three notifications for the same Pokemon within minutes. These pokemon are in `ALWAYS_NOTIFY_IDS` field of the config.py file. 
Any ideas what might be causing this? 

My scan and notifications settings are:
`SCAN_DELAY = 600`
`GIVE_UP_KNOWN = 600`
`GIVE_UP_UNKNOWN = 600`
`SKIP_SPAWN = 1200`
`ENCOUNTER = 'all'`
`NOTIFICATION_CACHE = 100`
With these settings I usually have Skipped=0 and Unnecessary=300 in 3 hours.

P.S. I've just noticed that with the last commit "Notifications sent" field in terminal remains 0 even after several notifications. Might be a bug?

**Comment by eq2kazial** [comment]
Also having this same issue, getting 2-3+ Telegram notifications per Pokémon.

**Comment by vlacorte** [comment]
Same here but have been receiving multiple notifications rather than just two or three. I'll try looking into this issue later today.

**Comment by skateskate** [comment]
@vlacorte 
I get this error:
 ```
File "test-notifications.py", line 11, in <module>
    from monocle.notification import Notifier
  File "/home/pluto/Monocle/monocle/notification.py", line 111, in <module>
    raise ValueError('Only set NOTIFY_RANKING or NOTIFY_IDS, not both.')
ValueError: Only set NOTIFY_RANKING or NOTIFY_IDS, not both.
```
even if in the `monocle/config.py` file I comment out `NOTIFY_RANKING` line.

**Comment by vlacorte** [comment]
@skateskate Set `NOTIFY_RANKING = None` instead of commenting it out.

**Comment by skateskate** [comment]
Ok thanks, now I get 'Failure' even if I receive the notification on my Telegram channel.

**Comment by vlacorte** [comment]
@skateskate Exactly what is happening to me; I'm trying to find a solution for this bug.

**Comment by vlacorte** [comment]
It appears that I found the bug! It's very straightforward: add a `return True` after line 399 (or so) in monocle/notification.py so that we have 

```
self.log.info('Sent a Telegram...')
return True
```

I'll submit a pull request after testing a bit further.

**Comment by skateskate** [comment]
Ok great, now I get 'Success' after running `test-notifications.py`.
I'll test this too and I'll let you know if anything goes wrong.
Thanks again.

**Comment by vlacorte** [comment]
@skateskate It seems to be working; even the 'Notifications sent' counter is being correctly incremented. Pull request submitted!
