### ISSUE TITLE
Boundaries grid does not move after map_start & map_end changes

### ISSUE THREAD

**Issue by atticusm** [Noctem/Monocle#148]
My apology if this is easy for some of you, however, I have been racking my brain trying to figure this out. I moved my map_start & end further to the left, but it still shows the old grid on the map. The workers do start in the correct coordinates (the updated start & end coordinates). Will this have any effect on the performance/detection and if so what is the best way to fix it? Thank you for helping someone who is in way over his head. Cheers. 

http://imgur.com/a/FBKGf

**Comment by atticusm** [comment]
Thank you stunnaspinz. I Control + C the script to modify the accounts.pickle, however, it's stuck at '6689 DB items pending.' Apparently my scan last night cannot be written do the database. I am using PostgreSQL on Ubuntu. Thank you for your help. Any ideas on why last nights scan will not write? 

Tell me where to order you pizza for helping. Very much appreciated.

**Comment by manolomanila** [comment]
Not sure if this might help, but you could try deleting your browser cookies/cache.

**Comment by atticusm** [comment]
Thank you for the suggestion manolomanila. I tried that as well. "ScanArea"
still shows outside the map start & end coordinates.

**Comment by manolomanila** [comment]
I assume you restarted _web.py_. What if you change it again and restart only _web.py_? Or try adding a Pokémon that is currently visible on the map to the trash list and restart _web.py_ to see if the change takes effect.

**Comment by atticusm** [comment]
THANK YOU manolomanila. All I needed to do was close web.py and re-launch. Box is now in the correct location. You are the true MVP. Have a good week.
