### ISSUE TITLE
One worker repeately throws MALFORMED RESPONSE error.

### ISSUE THREAD

**Issue by Aethios** [Noctem/Monocle#151]
I have one singular worker, in an army of more than 600, who repeatedly and continuously throws a MALFORMED RESPONSE error. The log reads "Missing GetMapObjects response. Giving up." That's it. Nothing else. No account name, no reason for the error, not even any attempts to fix it. Just that one line, hundreds of times per day. I don't know which account is the problem or I would remove it, and I don't know how to find out which account it is since workers are assigned randomly.

**Comment by Avatar690** [comment]
Workers are assigned incrementally from your config file starting with the top (worker0) all the way to the end (with 600 workers, the last worker would be worker599).

Check your scan.log.  Likely, this account received the hammer.

**Comment by Aethios** [comment]
The message above is all that appears in the scan.log, over and over and over. There is no further information. If an account has been banned, I haven't been given any indication. The script makes no attempt to swap it with one of the 58 accounts I have in reserve. I wouldn't even mind to remove it from the list manually, but I don't know which one to remove since the log doesn't tell me which account is the one causing problems.

**Comment by thordurk91** [comment]
Fixed in 86ec785e0e41c0fcf1db9d9c0723563513e752a3 

"Check account when GMO response is missing"

**Comment by Aethios** [comment]
Pulled the latest update and this issue is fixed. Thanks.
