### ISSUE TITLE
Show area name in status message (feature request)

### ISSUE THREAD

**Issue by thordurk91** [Noctem/Monocle#153]
would help a bunch if you couple of similar instance because sometimes the instance halts when exiting and you have to kill the cmd prompt and cd back to the instance you just killed. But on windows the python window and the default command prompt doesnt show what your working directory is

So my request is to add the area name from the config to the def get_status_message(self) function in overseer 

for example 
```
...
output = [
'Area name {}'.format(config.AREA_NAME),
...

]

```

**Comment by stunnaspinz** [comment]
I agree with this request. I have myself modified overseer to have the name of the area in use due to having multiple instances on single machine.
