### ISSUE TITLE
Account Level?

### ISSUE THREAD

**Issue by xLeevo** [Noctem/Monocle#154]
Hey, is there ANY solution for checking the lv of the accounts without just loggin in with them? i mean something like a little script for monocle or some script to check the trainer lv only/at least.. i had a script for checking the status if banned, server issue oder normal login, but is there any script for this? i would need that for monocle so far

**Comment by m3g4mInD** [comment]
@xLeevo  go to path scripts and send/copy file   print_accounts.py to root monocle then   
 python3 print_accounts.py

**Comment by xLeevo** [comment]
Thank you very much !

**Comment by xLeevo** [comment]
So now i got the problem that this script isnt showing the lv, inventory etc anymore, but it was all fine.
I tried it before, after and while monocle was scanning. nothing helped tho.
here is a screen what i mean:
http://puu.sh/upvSL/cbd7c63427.png
(Password isnt relevant to hide because the usernames are cut)
