### ISSUE TITLE
Script "Print_Accounts.py"

### ISSUE THREAD

**Issue by xLeevo** [Noctem/Monocle#155]
So now i got the problem that this script isnt showing the lv, inventory etc anymore, but it WAS all fine.
I tried it before, after and while monocle was scanning. nothing helped tho.
here is a screen what i mean:
http://puu.sh/upvSL/cbd7c63427.png
(Password isnt relevant to hide because the usernames are cut)

Btw there is still one account with these more information, and the time stamp is there too. so what can i do to fix this for all?

**Comment by xLeevo** [comment]
For now it is working again, but the information about the level is out of date when i am starting it. For example the first account was lv 3 and the script printed out that this acvcount is level 1, any advices for getting information more up to date?

**Comment by Noctem** [comment]
The account level should get updated whenever it logs in (and possibly more frequently soon), and then updated in the pickle at the top of each hour. Since the original issue is gone, I'll close this.
