### ISSUE TITLE
"WARNING xxxx is not authenticated.", "Swapping out xxxx because login failed."

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#16]
messages like that have increased

**Comment by evenly-epic-mule** [comment]
but the login seams to work later on again, have like 7-9 reports on some accounts that are currently running

**Comment by Noctem** [comment]
Yeah, pgoapi seems to fail to reauthenticate most (if not all) of the time. It hasn't been a high priority for me to fix that since I don't mind having my workers shuffled periodically, but the root cause should probably be discovered.

**Comment by evenly-epic-mule** [comment]
I noticed that I now have some other errors with "[   ERROR][pgoapi.pgoapi] Request for new Access Token failed! Logged out..."
but I'd gues that they are because scan.py segfaulted and so the current auth token wasn't written back and It tried using a old one

**Comment by n30nl1ght** [comment]
Push

I have the Same Problem.
The message comes often
```
[2017-01-28 05:01:21,677][ WARNING][worker-114] pokegobern155 is not authenticated.
[2017-01-28 05:01:23,728][ WARNING][worker-114] Swapping out pokegobern155 because login failed.
```

I run my server with Hash-Key

Whats the Problem. Give it a solution?

**Comment by n30nl1ght** [comment]
Account are Banned or you forget to activate

**Comment by evenly-epic-mule** [comment]
Haven't had that error for a while, as everything has been changed => closing
