### ISSUE TITLE
2captcha support

### ISSUE THREAD

**Issue by vlalo001** [Noctem/Monocle#17]
Hey Noctem, do you plan on adding 2captcha support soon? I tried to implement it myself but can't seem to debug it using the "logger.info" method. I'm going to keep trying but I was wondering if you plan on implementing it yourself.

Thanks for your work!

**Comment by Noctem** [comment]
Addressed this on [Discord](https://discord.gg/RVuXKyg) already, but for those that didn't see: it's not currently a high priority for me since my CAPTCHA rates are so low, but I'm open to accepting a PR for it.

**Comment by evenly-epic-mule** [comment]
I'd say this can be closed:  https://github.com/Noctem/pokeminer/commit/af447515149b553de18d9f3a3dd4f394d9534f74
