### ISSUE TITLE
INVALID_REQUEST from all workers

### ISSUE THREAD

**Issue by tcolar** [Noctem/Monocle#170]
I was using it fine earlier today (latest version as of noon today) but all a sudden all my workers are getting INVALID REQUEST
```
Monocle running for 0:00:09.897763
Known spawns: 11, unknown: 22, more: 0
4 workers, 2 threads, 6 coroutines
DB queue: 0, sightings cache: 0, mystery cache: 0

Seen per worker: min 0, max 0, med 0
Visits per worker: min 0, max 0, med 0
Visit delay: min 0.0, max 0.0, med 0.0
Speed: min 0.3, max 0.6, med 0.5
Extra accounts: 0, CAPTCHAs needed: 0

Pokemon found count (10s interval):


Visits: 0, per second: 0.00
Skipped: 1, unnecessary: 0

Workers without sightings so far:
0, 1, 2, 3

X X
X X
[W0: INVALID REQUEST]   [W1: INVALID REQUEST]   [W2: INVALID REQUEST]   [W3: INVALID REQUEST]
Coroutine completion timed out, moving on.
Dumping pickles...
Updating spawns pickle...
Closing pipes, sessions, and event loop...
Done.
```

I'm able to log into the worker account fine on my phone and also tried from a different IP with the same result, so don't think it's an account/ IP ban. (also tried deleting the db).

Any ideas ?

**Comment by ArgDave** [comment]
Yep. Same here.

**Comment by cyanosis78** [comment]
same here

**Comment by atticusm** [comment]
Same.

**Comment by tcolar** [comment]
FWIW it works if using a bossland key

**Comment by atticusm** [comment]
Thank you, Thibaut! Question. I currently use 20 accounts to scan my small
area. I haver been reading up on bossland keys, but I figure with those 20
accounts I would go over even the 1,000 RPMs. I only wish to scan a 7-8
mile radius from my house. Would it be better if I reduced those accounts
to 5 and used a bossland key? I am still learning. Thank you for the
information.

**Comment by tcolar** [comment]
@atticusm I'm not an expert on the matter, but my key is 150RPM and that allows about 4 account, but I think it depends of your settings (encounter pokemons, spin stops etc...)
I'm using 4 accounts and it says I'm around 144 RPM. S0 a 1k key should allow ~25 accounts or so ?

**Comment by baskettcase** [comment]
@atticusm @tcolar with 150 RPM key you should be able to run around 48 accounts. So your 20 accounts it shouldn't be a problem whatsoever.

**Comment by tcolar** [comment]
Yeah @baskettcase I was reading 144/150 as I'm using 144/150 but in fact it means 144 Available, so yeah should be able to do plenty.

**Comment by Noctem** [comment]
It seems that the old hashing may finally be dead. I don't intend to spend any time trying to fix it, it's crazy that Niantic allowed it to work this long (albeit with a flood of CAPTCHAs). Unless it starts working again or someone manages to fix it, I will just remove support for it from aiopogo.

So I'm closing this issue. It can be reopened if anyone's encountering this with the new hashing.
