### ISSUE TITLE
Up and running but doesnt seem to be doing anything.

### ISSUE THREAD

**Issue by RonnieBlaze** [Noctem/Monocle#182]
I think i have it up and running, i can see the scan in my console and it says my workers are working, but they only seem to be bootstrapping buy the console display.. 

I have my map start and stop set to a small park to cut down on the area they are working in.

anything i should check in the config?

**Comment by DavePlater** [comment]
The part that got me was that you need a hashing key from bossland for it to work. (I think this was a recent-ish change)
Everything looked like it was working in the console except the coroutines number was really high and there was no encountering of pokemon. (Also when looking at the map via web.py my workers never showed up)

I bought a key from bossland and everything started working.

**Comment by RonnieBlaze** [comment]
thank you I will look into getting a hashing key. 

how did you connect to the web.py when its running? i am running this on another computer and when i ran the web.py it gave my localhost to connect to, but i tried my servers ip:port but nothing came up.

**Comment by DavePlater** [comment]
See #124 where @n30nl1ght explains how to use the arguments to web.py -H for the ip and -P for the port

**Comment by RonnieBlaze** [comment]
sweet! thanks again

**Comment by DavePlater** [comment]
Did you get up and working? Is so then this issue should be closed.

**Comment by RonnieBlaze** [comment]
I still have to get the hashing, but that will probably fix my issue so i will close it. Thanks
