### ISSUE TITLE
Last update doesn't launch the scanner.

### ISSUE THREAD

**Issue by Rogunix** [Noctem/Monocle#189]
Hello,

Using the same configuration as I had on the previous version the scanner doesn't run on the last update. I tried to analyze the commit and see the new changes but I couldn't find a way to make it work again.

I add a screenshot of the freeze state, am I missing anything?

![monocleupdate](https://cloud.githubusercontent.com/assets/1291381/24082309/d548c70c-0cc3-11e7-90ee-425b9165f623.jpg)

Thanks in advance!

**Comment by DavePlater** [comment]
i havent upgraded yet, but the standard thing to try based on past issues seems to be running scan.py with the --bootstrap option so that it will search for spawn points again?

**Comment by MiguelGallegoRO** [comment]
Same problem here...

**Comment by baskettcase** [comment]
I reverted mine to the version right before this last commit since I was having the same problem.

**Comment by evenly-epic-mule** [comment]
I'd guess it is #190, could you check your scan.log?

**Comment by bikthor** [comment]
I'm having the same problem.

**Comment by MiguelGallegoRO** [comment]
The scan.log

[scan.txt](https://github.com/Noctem/Monocle/files/855040/scan.txt)


At the end of scan.log...

TypeError: 'NoneType' object is not callable
[2017-03-19 15:53:56][   ERROR][overseer] A wild TypeError appeared while updating spawns!
Traceback (most recent call last):
  File "/home/miguel/Monocle2/Monocle/monocle/overseer.py", line 352, in update_spawns
    await run_threaded(spawns.update())
  File "/home/miguel/Monocle2/Monocle/monocle/shared.py", line 72, in run_threaded
    return await LOOP.run_in_executor(x, cb, *args)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable


Yep, the #190, thank you evenly-epic-mule!

**Comment by evenly-epic-mule** [comment]
Could you close the issue then?
