### ISSUE TITLE
Help with Python

### ISSUE THREAD

**Issue by Nico1300** [Noctem/Monocle#193]
Hello Guys :) sorry I'm really new here and i doesn't know anything so correct me if something is wrong ^^
I need help with Python. Can someone give me a step by step Tutorial (i know the commands put not where i have to write them. I tried many things but nothing works. Would be nice if someone could help me thanks.
Sorry for bad English i'm from Austria (not Australia)

**Comment by DavePlater** [comment]
The README.md file has some basic instructions.
Are you getting a particular error when you run one of the py files?

**Comment by Nico1300** [comment]
Yeah the command is not found. And the Readme is very 'imprecise'. Do i have to write Python before i can use any python command? Some Install Commands work then but not the pip3 only pip and with pip is an error.

**Comment by Dracon23** [comment]
Questions: operating system, Python version?

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Nico1300 <notifications@github.com>
Gesendet: 23.03.2017 4:33 nachm.
An: Noctem/Monocle
Cc: Subscribed
Betreff: Re: [Noctem/Monocle] Help with Python (#193)


Yeah the command is not found. And the Readme is very 'imprecise'. Do i have to write Python before i can use any python command? Some Install Commands work then but not the pip3 only pip and with pip is an error.

**Comment by Nico1300** [comment]
Win 10 / Python 2.7.12

**Comment by DavePlater** [comment]
The instructions explicitly say you need python 3

**Comment by Nico1300** [comment]
Omg i just saw the 7 and thought i'm higher ... Thank you so much :)
