### ISSUE TITLE
Bug around Greenwich Meridian

### ISSUE THREAD

**Issue by MiguelGallegoRO** [Noctem/Monocle#197]
IV's and moves never works at the left side of the Greenwich Meridian in Spain, I tested it by putting it right in the middle, look at the picture. At negative longitudes the error happens 

![img_20170328_162251](https://cloud.githubusercontent.com/assets/25725567/24411355/f57c74e2-13d5-11e7-84a1-fcbbd2e1b2ee.jpg)

**Comment by MiguelGallegoRO** [comment]
A friend found the error, at worker.py

spawn_id = '0'+hex(pokemon['spawn_id'])[2:], instead of: spawn_id = hex(pokemon['spawn_id'])[2:]

**Comment by Noctem** [comment]
Fixed.
