### ISSUE TITLE
Error executing 'python3 create_db.py'

### ISSUE THREAD

**Issue by Jeroen196** [Noctem/Monocle#200]
When executing the 'sudo python3 create_db.py' command the function returns an error. From the file 'sanitized.py', the Config class raises an error with the following output:

> ~/Desktop/Monocle/Monocle$ sudo python3 create_db.py
Traceback (most recent call last):
  File "create_db.py", line 3, in <module>
    from monocle import db
  File "/home/jeroen/Desktop/Monocle/Monocle/monocle/db.py", line 15, in <module>
    from . import utils, bounds, spawns, db_proc, sanitized as conf
  File "/home/jeroen/Desktop/Monocle/Monocle/monocle/utils.py", line 29, in <module>
    from . import bounds, sanitized as conf
  File "/home/jeroen/Desktop/Monocle/Monocle/monocle/bounds.py", line 3, in <module>
    from . import sanitized as conf
  File "/home/jeroen/Desktop/Monocle/Monocle/monocle/sanitized.py", line 267, in <module>
    sys.modules[__name__] = Config()
  File "/home/jeroen/Desktop/Monocle/Monocle/monocle/sanitized.py", line 253, in __init__
    raise TypeError(err)
TypeError: ENCOUNTER must be str. Yours is: builtin_function_or_method.

Does anyone know how to solve this problem?

The config class from where the error is returned is as follows:

`class Config:
    def __init__(self):
        self.log = getLogger('sanitizer')
        for key, value in (x for x in vars(config).items() if x[0].isupper()):
            try:
                if isinstance(value, _valid_types[key]):
                    setattr(self, key, value)
                    if key in _defaults:
                        del _defaults[key]
                elif key in _defaults and value is _defaults[key]:
                    setattr(self, key, _defaults.pop(key))
                else:
                    valid = _valid_types[key]
                    actual = type(value).__name__
                    if isinstance(valid, type):
                        err = '{} must be {}. Yours is: {}.'.format(
                            key, valid.__name__, actual)
                    else:
                        types = ', '.join((x.__name__ for x in valid))
                        err = '{} must be one of {}. Yours is: {}'.format(
                            key, types, actual)
                    raise TypeError(err)
            except KeyError:
                self.log.warning('{} is not a valid config option'.format(key))`

**Comment by DavePlater** [comment]
Sounds like somewhere an assignment from the result of a function is supposed to happen but the parenthesis are missing so it is trying to assign the function itself?
Example: You wanted  MyFunction() but instead have just MyFunction

**Comment by MiguelGallegoRO** [comment]
Can I see your config.py?

**Comment by Jeroen196** [comment]
Thanks guys, I've found the problem. The problem was indeed in the config.py. After the 'ENCOUNTER = <string>' part, I had left out the quotation marks at 'all'. This caused the command 'all' to not be converted to a string, giving the error. Thanks for the help though :+1:
