### ISSUE TITLE
Telegram ClientOSError

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#203]
I'm getting no notifications at all and this in the log file:

`[2017-04-02 15:22:40][   ERROR][notifier] ClientOSError during Telegram notification.`

Does anyone have/had any similar issue?

**Comment by manugf** [comment]
Mac computer? 
I think, this is a problem in Python 3.6 with MacOS Sierra. This Python version comes with its own openSSL and doesn't have access on Mac root certificates.
Install [certifi](https://pypi.python.org/pypi/certifi)

**Comment by manolomanila** [comment]
Thank you manugf. Yes, Mac but with Yosemite. May still have the same or a similar problem.

Installed certifi but the problem persists (didn't restart the system and will do later just in case).

**Comment by manugf** [comment]
This worked for me. But you can try another solution:
Run an install command shipped with Python 3.6. I hope it will work.

`cd /Applications/Python\ 3.6/`
`./Install\ Certificates.command`

**Comment by manolomanila** [comment]
Nailed it! Thank you again manugf, that fixed the issue!
