### ISSUE TITLE
Expired (but not) Hash Key?

### ISSUE THREAD

**Issue by licorice917** [Noctem/Monocle#204]
I'm using the windows version and purchased a Bossland hash key.  I can run Pokefarmer no problem with the same key and have set up my account there and the key is valid, but I cannot seem to get Monocle to run with the same hash key.  Any suggestions on something I might of missed?

![monocle](https://cloud.githubusercontent.com/assets/4859837/24588183/2592737a-1778-11e7-86ec-3fb680a433d9.jpg)

**Comment by DavePlater** [comment]
Did you start from a clean slate when you put in your bossland key? I would say start with a clean clone and run through the steps again?

**Comment by licorice917** [comment]
Will try from the beginning again and let you know.

**Comment by licorice917** [comment]
No luck with a fresh install and the same error.  Is there something on the Bossland side that I need to do with my account as well?

**Comment by DavePlater** [comment]
I did not have to do anything extra, I just bought a key from bossland by following [https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer](url) and then pasting it into my config.py and UN-commenting the line.
You have double checked that your monocle/config.py instance as your correct key and the line is not still commented out?

**Comment by licorice917** [comment]
Dave--is the link you have above the same as buying the key from Pokefarmer.com or it is a different service that is offered by Pokefarmer for hashing?

**Comment by DavePlater** [comment]
I do no think pokefarmer is the same thing as a bossland hashing key. You need a key from bossland, not pokefarmer. 
If you can afford another 4euros, I would suggesting just buying one from those links. I cannot guarantee anything, but I bought mine from there and it has been working.

**Comment by Dracon23** [comment]
Pokefarmer keys are NOT the same as Hash keys.

**Comment by licorice917** [comment]
That would solve it, thanks!!

**Comment by mimikq** [comment]
Hi All

i have q , till now i was using RM, but now i'm trying monocle. i i got error : KeyError: 'HASH_KEY'

from what i read around in issues opened or closed, so RM and monocle are not using the same HASH KEY ?

    https://talk.pogodev.org/d/55-api-hashing-service-f-a-q
    https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

i got 1 one but it looks like i will need the 2. ?

thx for answer

**Comment by walaoaaa1234** [comment]
@mimikq RM and monocle is using the same hash key. This issue is talking about "pokefarmer bot" key is not the same with the hash key we use for RM/Monocle.
set your hash key in ``config.py``
```
HASH_KEY = '1A2B3C4D5E6F7G8H9I0J'
```

**Comment by mimikq** [comment]
@walaoaaa1234  hi thx for answer i got the HASH key there but still i got this error

**Comment by walaoaaa1234** [comment]
@mimikq did you copy ``config.example.py`` into ``.\Monocle\monocle\config.py``?
and make sure ``HASH_KEY = '1A2B3C4D5E6F7G8H9I0J'`` don't have ``#`` in front.
run ``python3 scripts/create_db.py`` and ``python3 scan.py``

**Comment by mimikq** [comment]
@walaoaaa1234 ok thx , i didn't copy config.py to monocle subdir right now it is there and looks like hash key is ok , right now i need to fight with :) ImportError: No module named 'MySQLdb'

**Comment by walaoaaa1234** [comment]
5. `pip3 install -r requirements.txt`
  * Optionally `pip3 install` additional packages listed in optional-requirements
    * *asyncpushbullet* is required for PushBullet notifications
    * *peony-twitter* is required for Twitter notifications
    * *gpsoauth* is required for logging in to Google accounts
    * *shapely* is required for landmarks or boundary polygons
    * *selenium* (and [ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/)) are required for manually solving CAPTCHAs
    * *uvloop* provides better event loop performance
    * *pycairo* is required for generating IV/move images
    * *mysqlclient* is required for using a MySQL database
    * *psycopg2* is required for using a PostgreSQL database
    * *aiosocks* is required for using SOCKS proxies
    * *cchardet* and *aiodns* provide better performance with aiohttp
    * *sanic* and *asyncpg* (and a Postgres DB) are required for web_sanic
    * *ujson* for better JSON encoding and decoding performance

you need ``mysqlclient``, ``pip3 install mysqlclient``

**Comment by walaoaaa1234** [comment]
@mimikq hmm, try delete the pickle folder and clean your monocle sql database
run ``python3 scripts/create_db.py`` after that

**Comment by mimikq** [comment]
@walaoaaa1234 still nothing :( i did exactly what you wrote. and DB is still empty and the same errors :(

**Comment by walaoaaa1234** [comment]
@mimikq join discord for more support
https://discord.gg/Wcv9zv
