### ISSUE TITLE
Large increase in "SessionInvalidated" errors

### ISSUE THREAD

**Issue by PoGoToledo** [Noctem/Monocle#206]
Not 100% sure on what happened. I've been having some issues with my larger scan area with the accounts getting stuck with the bootstrapping symbol and my Visits per second being all the way down to 0.04 or so. And now when I went to start my instances back up, I have been getting a large number of "SessionInvalidated on BlahBlahBlah". Whether it is GetMapObjects, Encounters and so on.

So far I have tried fully uninstalling python36 and reinstalling it (along with all requirements and some of the optional for PostGreSQL). I've tried using a new database, one locally on my machine and one on my VPS. I've tried changing options in the config such as "ENCOUNTER =", "SIMULTANEOUS_SIMULATION", "BOOTSTRAP_RADIUS", "SPAWN_ID_INT", "COROUTINES_LIMIT =". 

Even tried doing a fresh pull on a fresh DB with unused accounts.

Any ideas as to what it may be, would be greatly appreciated!

**Comment by mykill18** [comment]
same here

**Comment by DavePlater** [comment]
Is SessionInvalidated coming from the pogo servers? That kind of sounds like when an account gets logged on somewhere else, the session key for the first account becomes invalid?

**Comment by PoGoToledo** [comment]
I'm not sure honestly. The accounts in question are freshly made so there isn't a way that they are signed in elsewhere.

**Comment by DavePlater** [comment]
Did they get made by hand or by the script? Withen the last week or so PTC changed how accounts are created, something to do with accepting terms of service and an extra captcha i think.
Any issues with that?

**Comment by PoGoToledo** [comment]
Some by hand and some by script. Accounts that were made months ago are having the issue as well. None of the accounts have a captcha needing to be solved. I do have my 2captcha key added to the config.

**Comment by PoGoToledo** [comment]
[2017-04-05 08:21:21][ WARNING][worker-281] SessionInvalidated on DownloadRemoteConfigVersion.
[2017-04-05 08:21:15][ WARNING][worker-113] SessionInvalidated on GetPlayerProfile.

Stuff like this just spams my log file.

**Comment by baskettcase** [comment]
I was told that if you revert to a previous version of Monocle and then uninstall pycrypt and install an older version of pycrypt then you'll be on the older API version without the session invalidated errors. Im going to try this tomorrow and see if it works. I went to the previous version of Monocle that uses the previous API and that has cut down on them, it hasn't completely gotten rid of them, but there are less thankfully.

**Comment by PoGoToledo** [comment]
I have a buddy that is running on the most recent version with no issues....so that's a bit strange...

**Comment by baskettcase** [comment]
Yeah that is strange.. if you can find out what versions of the requirements he is using.. maybe that's the difference...

**Comment by PoGoToledo** [comment]
https://gyazo.com/737eed00433be9a074d1643dd63df893

This is what I'm using right now.

**Comment by baskettcase** [comment]
That doesn't say your exact versions, just that it's equal to or greater than the required versions...

**Comment by PoGoToledo** [comment]
https://gyazo.com/9a9f92f6f941762fbd5468245338e51a

There we go

**Comment by baskettcase** [comment]
But it's not working for you right? Can your buddy send us a similar screenshot? What command did you use to get that nice list? I was getting the version per package, pip show <packagename> but that's long and tedious! :)

**Comment by PoGoToledo** [comment]
"pip freeze"

He is at work right now. But he said he'll get it to me when he can.

**Comment by PoGoToledo** [comment]
It seems I'm on pycrypt 0.5.0 and he is on pycrypt 0.1.1....so when I get home I'm going to downgrade and see what happens.

**Comment by PoGoToledo** [comment]
Downgrading worked! =D No more Session Invalid errors!

Just do
pip uninstall pycrypt
pip install pycrypt==0.1.1

**Comment by baskettcase** [comment]
Thanks! Although boy that's a huge downgrade.. I wonder if that will cause other problems?

**Comment by baskettcase** [comment]
I tried this and all I got were exceptions, nothing was working :(

**Comment by PoGoToledo** [comment]
https://gyazo.com/e4665fb86908c4f3b438fba4270fdd31

This is my list of installed python libs now and I am running with no Session Invalid errors now.

**Comment by PoGoToledo** [comment]
It could of also been because my aiopogo was at 1.6.1....I'm not sure. All I know is that I'm running now xD

**Comment by baskettcase** [comment]
These are the differences from mine from yours:

aiopogo==1.6.1
asyncpushbullet==0.12.10
python-magic==0.4.12
selenium==3.3.1
Shapely==1.5.17.post1
SQLAlchemy==1.1.9

**Comment by PoGoToledo** [comment]
I would try downgrading aiopogo and SQLAlchemy. One at a time and see if it helps.

**Comment by dumbbird** [comment]
Hi,

I tried 

```
pip uninstall pycrypt
pip install pycrypt==0.1.1
```

and it does clear the Session Invalid errors, however the program errors out even earlier at:

>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopogo/rpc_api.py", line 238, in _build_main_request
>     sig.SerializeToString(), sig.timestamp_ms_since_start)
> TypeError: function takes exactly 3 arguments (2 given)

So i'm still hanging on it here. Any clues?
