### ISSUE TITLE
Unable to connect to manager for worker data

### ISSUE THREAD

**Issue by canadianoob** [Noctem/Monocle#207]
Hi, I'm new here and I just installed the app following the section "Setting up".
I read all the issues thread but nothing could help me.
When I launche web.py , I keep getting repeatedly the mesage "Unable to connect to manager for worker data."

![image](https://cloud.githubusercontent.com/assets/26912328/24683868/fa139b30-196f-11e7-927a-82041c80ac5b.png)

I can see nothing but blue square on map.

I'm currently testing with 1 working account.
My accounts.csv looks like :

username,password,provider,model,iOS,id
xxxxxx,xxxxxx,ptc

In config, all i changed is ; 
MAP_START, MAP_END and
PLAYER_LOCALE = {'country': 'CA', 'language': 'en', 'timezone': 'Canada/Eastern'}

Thank you.

**Comment by licorice917** [comment]
I'm getting the same on my web.py launch.  Timezone should be America/Toronto for EDST (not Canada).

**Comment by DavePlater** [comment]
I assume you also ran scan.py first? (Just checking)

**Comment by canadianoob** [comment]
@licorice917 I changed but no change.
@DavePlater Yes

**Comment by DavePlater** [comment]
You do not have multiple instances running do you?

**Comment by canadianoob** [comment]
@DavePlater No i'm not.
I restart web.py each time i make change in files.

**Comment by DavePlater** [comment]
What is the MANAGER_ADDRESS set to in your config.py?
Since config.py is shared between scan.py and web.py they should always think it is the same value, but web.py isn't making the connection.
Are you on windows or linux?

Did you remember to put in your bossland key into the config so the scan.py would actually work?
What is in your scan.log? Maybe the problem is with scan.py and not web.py

**Comment by canadianoob** [comment]
@DavePlater I'm on windows. 
Is bossland key necessary to run? I thought using old hash key because I didn't want to buy it. 
If yes, I'll close this thread.

**Comment by DavePlater** [comment]
Yes bossland key is needed now, you need to make sure you get the api key [https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer](https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer) and not the pokefarmer account key.

I am not sure that will solve your issue with "Unable to connect to manager for worker data." but it should at least make your scan.py start finding things.
