### ISSUE TITLE
replace longest running account

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#21]
currently accounts are rotated by replacing the account with the lowest sighting rate.
If you now have a scanner running over a city + rural area this means that the account further out get replaced regularly but the inner ones don't => the will be captchad

It would be grate if someone would change this.
Maybe replace the lowest + longest.
Additionally one may add a ROTATE_INTERVAL option, as you may like to rotate more often if you are using more workers.

**Comment by Noctem** [comment]
Yeah, I've been intending to make that more configurable for a while as part of my ongoing quest to replace magic numbers with configuration options. I should get to it soon.

**Comment by evenly-epic-mule** [comment]
has been implemented
