### ISSUE TITLE
Workers won't move

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#210]
Fresh installed on mac (same one I mentioned on issue #203 just for reference that everything else seems to work) but the workers won't move.

If I run bootstrap there is nothing in the log file after starting bootstrap phase 2. After a few hours, all the workers are still in the same place.

I've let a scan instance running for days while trying to figure out why, and they discovered their nearby spawnpoints, but there is still no movement (discover new spawnpoints enabled).

I've already tried what is suggested on issue #138 without luck, and with different speed limits.

**Comment by DavePlater** [comment]
None of my instances are working anymore, I just get "invalid requests", are yours doing that?

**Comment by manolomanila** [comment]
I started getting pogoapi error but solved it pulling.

Also found the issue; speed_unit (what ever you choose / hour) is bound to speed_limit (wasn't like that before) and I had 15 meters/hour... changed it to kilometers and done.
