### ISSUE TITLE
Syntax error on worker.py

### ISSUE THREAD

**Issue by manugf** [Noctem/Monocle#235]
Line 694 
`cell_ids = self.get_cell_ids(point)`
the function get_cell_ids requires two input params but only one tuple is passed.
You need to unpack the tuple or change the function definition in order to accept the point tuple.

Line 694 should be 
`cell_ids = self.get_cell_ids(*point)`

**Comment by evenly-epic-mule** [comment]
which version / commit are you using? is it up to date?

**Comment by manugf** [comment]
Downloaded yesterday and getting the same error.
`[2017-04-19 04:07:23][   ERROR][worker-16] A wild TypeError appeared!
Traceback (most recent call last):
  File "/home/user/Monocle/monocle/worker.py", line 606, in visit
    return await self.visit_point(point, spawn_id, bootstrap)
  File "/home/user/Monocle/monocle/worker.py", line 697, in visit_point
    cell_ids = self.get_cell_ids(point)
TypeError: GetCellIDs() takes at least 2 arguments (1 given)`

solved again adding an asterisk
