### ISSUE TITLE
Individual IV's and movesets

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#244]
I confirmed it myself, IV's and movesets are now different and bound to trainer level from 1 to 25. From 25 to 40 is the same.

Source: https://www.reddit.com/r/TheSilphRoad/comments/66m5rl/pokemon_stats_now_appear_dependent_on_trainer/

Solutions:

- Level up every worker to level 25. If Monocle is set to catch mons it will become another bot to level up accounts, so I would rather look for something different.

- Level up a few accounts to level 25 (manually?) which will encounter mons that are eligible for notifications / IV checking. (Could even have a few at 30 to also check CP and add it as a new feature...)

Any other ideas?

Edit: I've been using Monocle for a while and still I don't have the knowledge to code and make pull requests, but if anyone is interested, I'm willing to help in any possible way for this or any other matter.

Edit2: No longer the same IV's below level 30. It now works as CP.
https://www.reddit.com/r/TheSilphRoad/comments/67ypx2/different_stats_and_moves_between_level_26_and/

**Comment by Jabsu** [comment]
Personally, I think catching and even evolving Pokémon is fine, as there's already egg incubating and PokéStop spinning, so it's not like Monocle is a *legit* software anyways. With the current methods, levelling accounts to 30 will take ages. I said 30, because the IVs and movesets are not **always** the same on 25-29 level accounts, according to someone on Reddit. Can't find the post right now.

And, of course, having level 30 accounts would mean there could be CP values on the map/notifications, which would be awesome.

**Comment by DavePlater** [comment]
Is this related to why some of my instances have stopped seeing any IVs in the encounter section?

**Comment by manolomanila** [comment]
> Is this related to why some of my instances have stopped seeing any IVs in the encounter section?

As far as I know, there should be no correlation. You should be still getting all the IVs corresponding to the level of the worker that encountered the mon.

**Comment by manolomanila** [comment]
@mewio could you be this guy? If not, he's taking the lead haha: https://www.reddit.com/r/pokemongodev/comments/682nxv/how_to_determine_the_lvl_of_a_wild_pokemon_for_30/

If you are still interested, I could try helping you gathering the data.

**Comment by mewio** [comment]
@manolomanila I am not that guy, but I would love to see his hypothesis verified. When he says pok-ID, does he mean what we call encounter ID?

Even if his approach doesn't pan out, there are other approaches that might, and we need data if we're ever going to test them.

Ideally, someone would set up a scanner with at least one account stuck at each level, encounter each pokemon with all accounts, and store the all the stats for each encounter. I'd like the stats to include pokemon IVs, trainer level & XP, spawn point details, date & timestamp... pretty much everything the servers tell us, even the things that might have seemed unimportant in the past. With enough of that, we could start looking for patterns and trying ideas.

**Comment by manolomanila** [comment]
Closing in favor to #258
