### ISSUE TITLE
Accounts flagged

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#249]
I haven't checked any accounts in a while but today I did and got the warning of using a third party client in all the accounts that I checked. Prior to this, I never got a warning with Monocle. Anyone have any thoughts?

With how things are proceeding lately (IV and moves per lvl, new Niantic support accounts on r/pokemongo, and a few other things) they might have changed something API related or be up to something. I'm stopping my scanner for a while to see if things settle down, and though some of you may want a warning just in case this is something.

**Comment by mewio** [comment]
Is there some way to check for these warnings other than logging in the the account using the official app?

**Comment by mewio** [comment]
Looks like feature request #266 would cover this.
