### ISSUE TITLE
How to collect all spawn points in area

### ISSUE THREAD

**Issue by jj11ct** [Noctem/Monocle#261]
Hi there, 

I have tried a few methods to get the workers to cover all spawn points, however they seem to only visit certain areas/bunch together - for those areas the pokemon are showing but I would like to collect spawn points for the whole map area.

<img src='https://i.imgur.com/Y5nlPR2.png' />

I ran the most recent scan for 8 hours, i know it is a large map area but a small percentage is being explored.

I have tried 
scan.py
scan.py --no-pickles
scan.py --bootstrap ( the workers do split up into a equidistant points, but there are gaps in between the workers and in this mode they just revisit the same point, and don't move into new areas)

<img src='https://i.imgur.com/BWjFIYJ.png' />

what am i missing here?

Thanks so much to anyone who can provide insight into this, I am loving this mapping tool, and would be eternally grateful for a poke in the right direction.

running with 50 accounts 
on a 150 rpm key that doesn't come close to maxing out at all.

SCAN_DELAY = 10
SPEED_UNIT = 'kilometers'
SPEED_LIMIT = 19.0

GRID = (7, 7) 

GIVE_UP_KNOWN = 75
GIVE_UP_UNKNOWN = 60
SKIP_SPAWN = 90
RESCAN_UNKNOWN = 90

GOOD_ENOUGH = 0.1

MORE_POINTS = True

Thanks,
J

**Comment by jj11ct** [comment]
tried reducing the mapping area.

<img src='https://i.imgur.com/YwnCzi7.png' />

**Comment by Ricola3D** [comment]
I'm experiencing the same issue. I'm currently trying --bootstrap with more bots and with a BOOSTRAP_RADUIS reduced to 20m. It seems the bots do not cluster as fast as with the default 130m but it is still very slow to get more spawnpoints in the empty spaces...

![image](https://user-images.githubusercontent.com/1682096/31912315-be995d60-b843-11e7-910a-dd60b809576c.png)
