### ISSUE TITLE
Blank Chrome page when trying to solve captchas

### ISSUE THREAD

**Issue by Plotin** [Noctem/Monocle#270]
As the title states, I am running scan.py and have captchas. I then run solve_captchas.py in a different cmd it it starts "doing stuff". It opens up a chrome window, that says it is being controlled by test software but the URL is data; and the page stays blank all the time.

I have installed selenium and chromedriver (monogen is working correctly so I asume the setup is fine)

Anyone has an idea what might me wrong?

**Comment by Plotin** [comment]
It seems to be a KeyError on line 118:
`responses = response['responses']`

**Comment by Jabsu** [comment]
Yeah, I had this problem too with Python 3.6.1. With 3.5.2 (which I had already installed for other projects) it works.

**Comment by walaoaaa1234** [comment]
```
L35
-     return response['responses']['VERIFY_CHALLENGE']['success']
+    return response['VERIFY_CHALLENGE'].success

L118
-    responses = response['responses']
-    challenge_url = responses['CHECK_CHALLENGE']['challenge_url']
-    timestamp = responses.get('GET_INVENTORY', {}).get('inventory_delta', {}).get('new_timestamp_ms')
+    challenge_url  = response['CHECK_CHALLENGE'].challenge_url
+    timestamp = response.get('GET_INVENTORY', {}).inventory_delta.new_timestamp_ms
```

**Comment by Plotin** [comment]
Yep, just figured it out myself, but thanks for the very quick reply!
