### ISSUE TITLE
Can't quit gracefully 

### ISSUE THREAD

**Issue by Karlos007** [Noctem/Monocle#298]
Sometimes after doing Ctrl + c I get stuck at this :
Dumping pickles...e, 3756 DB items pending   s pending   
3757 DB items pending

And if that happens, when I start the app again doesn't show mons, should I delete all and start again the DB or I can repair the spawn DB?

Thanks

**Comment by DavePlater** [comment]
I get this a lot too.
Normally I have to run scan.py --bootstrap in order to get it up and running again

**Comment by Karlos007** [comment]
Thanks :) I'll try it if happens again.

**Comment by ifindpokemons** [comment]
Do you have multiple instances of Monocle running when this occurs?

**Comment by Karlos007** [comment]
Nope. But it's been running all night fine.

I don't know if it will give the error when I exit.
