### ISSUE TITLE
Hash Key appears to have expired

### ISSUE THREAD

**Issue by Karlos007** [Noctem/Monocle#309]
[2017-06-26 18:44:18][   ERROR][worker-15] 5T6A0V4S1X... appears to have expired.

Then it closes, but the hash key is fine and starting again works, is this an issue with bossland or the app?
Also the program should try again instead of quitting entirely.

5T6A0V4S1X... appears to have expired.
Exiting, please wait until all tasks finish
Finishing tasks...
Dumping pickles...ve, 0 DB items pending   
Closing pipes, sessions, and event loop...
Done.
ubuntu@ubuntu-01:~/Monocle$ 

And thanks for the effort of making this app.

**Comment by osxy** [comment]
This is a bosslands problem sadly.

Verstuurd vanaf mijn iPhone

**Comment by jackey1510** [comment]
I got this problem quit often as well. Sometimes it stops after a very short period of time, which is quite annoying. I am trying to comment out exit() in line 713 of workers.py and it should be able to retry.

**Comment by Karlos007** [comment]
I'm also trying this command to auto exec after crash

_while true; do python3 scan.py; done_

**Comment by EFMEX505** [comment]
bossland issue, nothing we can do sadly

**Comment by manolomanila** [comment]
Didn't see this post and wrote #311 . The error details seems a bit different in windows.
