### ISSUE TITLE
scan.py segfaulting

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#36]
Sometimes scan.py is segfaulting - this only seams to happen when there still are mysterys
after segfaulting there still is one process with a thread left over
there are no extra error messages or something like that

here some times:
Tue 17 Jan 09:20:06 CET 2017
Tue 17 Jan 09:58:31 CET 2017
Tue 17 Jan 10:51:27 CET 2017
Tue 17 Jan 11:38:59 CET 2017
Tue 17 Jan 12:06:26 CET 2017

**Comment by Noctem** [comment]
What do you mean it only happens when there are still mysteries? Does it run out of memory?

**Comment by evenly-epic-mule** [comment]
No I'm not running out of memory.
And well lets say it so, if I have mysteries I get segfaults and the longest runtime seams to be 8 hours.
after all mysteries have been resolved the scanner runs until I stop it

**Comment by Noctem** [comment]
Still experiencing this? Could it be related to ulimits?

**Comment by evenly-epic-mule** [comment]
nope, no ulimits in place, but I haven't hat it for a while so I'll close it
