### ISSUE TITLE
not scanning points, while workers are inactive

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#37]
![pkmn](https://cloud.githubusercontent.com/assets/22026252/22020234/78524668-dcb7-11e6-9d15-12cd3dc0be84.png)
![pkmn](https://cloud.githubusercontent.com/assets/22026252/22020252/92870a32-dcb7-11e6-8c11-34019c20c525.png)

**Comment by m3g4mInD** [comment]
For me was no pokemon when they are active after 12hrs scan,but if i check login with pogocaptcha they login and start scan again and find pokemons.

**Comment by evenly-epic-mule** [comment]
![pkmn-hanging-partial](https://cloud.githubusercontent.com/assets/22026252/22068288/df9833ae-dd94-11e6-88a0-5da7e674c5d7.png)
![pkmn-hanging-partial2](https://cloud.githubusercontent.com/assets/22026252/22068289/dfad4992-dd94-11e6-851b-63766506ff3f.png)
![pkmn-hanging-partial3](https://cloud.githubusercontent.com/assets/22026252/22068290/dfd4fca8-dd94-11e6-952a-89ffb9dc315c.png)
![pkmn-hanging-partial4](https://cloud.githubusercontent.com/assets/22026252/22068292/dfd5d1a0-dd94-11e6-83a6-518f18e9b23e.png)
![pkmn-hanging-partial5](https://cloud.githubusercontent.com/assets/22026252/22068291/dfd789f0-dd94-11e6-97e1-82d666774377.png)
![pkmn-hanging-partial6](https://cloud.githubusercontent.com/assets/22026252/22068293/dfd7bba0-dd94-11e6-902a-8592a7c9f29c.png)
![pkmn-hanging-partial7](https://cloud.githubusercontent.com/assets/22026252/22068294/dfdad3bc-dd94-11e6-9334-977deefdd1c5.png)
looks like the workers are hanging / not releasing the `self.coroutine_semaphore`

**Comment by evenly-epic-mule** [comment]
I've started timing the try_point method:
Seconds per: Visit: 10.03, Try: 27.99, Select Worker: 0.14

for some reason the time the try_point method needs seams to be increasing more and more

**Comment by evenly-epic-mule** [comment]
Now I'm counting how many coroutines are in which state
Current: worker.visit 1, best_worker 199, best_worker Sleep 199

**Comment by evenly-epic-mule** [comment]
Ok, I think I know what the problem is...
It seams like there are not enouth workers / to many workers with to high distance

This can happen if:
1. you have the workers all on mysterys (workers clustering)
2. your region is to big for the number of workers you have

**Comment by Noctem** [comment]
I'm not sure I understand. You seem to be talking about a few different things. What is the problem here? Why do you think that `coroutine_semaphore` isn't released?

**Comment by evenly-epic-mule** [comment]
sry, `coroutine_semaphore` was one of my first thoughts, ignore that one

**Comment by Noctem** [comment]
Is there still a problem here? If so, what is it?

**Comment by evenly-epic-mule** [comment]
haven't encountered this Problem for a while, closing
