### ISSUE TITLE
Unable to install MySQLClient

### ISSUE THREAD

**Issue by ARGG1** [Noctem/Monocle#47]
Hi @Noctem 

I ran: pip3 install mysqlclient but got:

    _mysql.c(29): fatal error C1083: Cannot open include file: 'my_config.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit
status 2

I am using MariaDB as the DB, hope that is OK. I have tried the above on two different computers.

**Comment by thordurk91** [comment]
I use pymysql instead

so my config looks like

`DB_ENGINE` = 'mysql+pymysql://{your mariadb info}'``

**Comment by ARGG1** [comment]
Hi @thordurk91 thanks for the suggestion. I installed it and set my DB_engine string as: DB_ENGINE =  'mysql+pymysql://pogomineruser:password@localhost/pogominerdb'

However next step calls for "Run python3 scripts/create_db.py from the command line"

There is no create_db.py in scripts folder.... 

Lastly, I ignored that step, and ran python3 scan.py ... however ended up with an error:

    return __import__('MySQLdb')
ModuleNotFoundError: No module named 'MySQLdb'


The instructions are leading me nowhere... Sorry.

**Comment by Noctem** [comment]
Sounds like you're not on the latest version. [create_db.py](https://github.com/Noctem/pokeminer/blob/develop/scripts/create_db.py) is there.

**Comment by ARGG1** [comment]
Thanks @Noctem I downloaded zip instead of doing git install. it was there.. here is the next error:

C:\PogoMap\pokeminer>python scripts/create_db.py
Traceback (most recent call last):
  File "scripts/create_db.py", line 3, in <module>
    from pokeminer import db
ModuleNotFoundError: No module named 'pokeminer'

What do there?

**Comment by Oxyde59** [comment]
Same problem here. Can't create DB
python3.5 pokeminer/scripts/create_db.py
Traceback (most recent call last):
  File "pokeminer/scripts/create_db.py", line 3, in <module>
    from pokeminer import db
ImportError: No module named 'pokeminer'

**Comment by GouSao** [comment]
same problem
Traceback (most recent call last):
File "pokeminer/scripts/create_db.py", line 3, in 
from pokeminer import db
ImportError: No module named 'pokeminer'

**Comment by n30nl1ght** [comment]
I have the Same Problem
```
pokemongo@kbs02:~/httpdocs$ python3 scripts/create_db.py
Traceback (most recent call last):
  File "scripts/create_db.py", line 3, in <module>
    from pokeminer import db
ImportError: No module named 'pokeminer'

```

**Comment by n30nl1ght** [comment]
Solv from Discordchat:
Move the create_db.py to main directory

**Comment by Oxyde59** [comment]
working fine for sqlite, but have another error for MySQL : 
  File "scan.py", line 125, in <module>
    from pokeminer.worker import Worker
  File "/root/pokeminer/pokeminer/worker.py", line 14, in <module>
    from .db import SIGHTING_CACHE, MYSTERY_CACHE, Bounds
  File "/root/pokeminer/pokeminer/db.py", line 371, in <module>
    Session = sessionmaker(bind=get_engine())
  File "/root/pokeminer/pokeminer/db.py", line 103, in get_engine
    return create_engine(DB_ENGINE)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
ImportError: No module named 'MySQLdb'

I use MariaDB and I have installed optionnal requirements mysqlclient
any idea ?

**Comment by n30nl1ght** [comment]
you can try installing pymysql and using that instead
you'd just change your config to, DB_ENGINE = 'mysql+pymysql://

**Comment by Noctem** [comment]
The issue with the pokeminer module not being found was fixed by moving the script to the base directory in 0cebbb7. If you still have problems with MySQL that aren't fixed by trying [alternative DBAPIs](https://docs.sqlalchemy.org/en/latest/core/engines.html#mysql), feel free to open a new issue.
