### ISSUE TITLE
Use nearby Pokemon for scanning targets

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#5]
so that we find more the rare Pokemon

I don't really yet understand the scanner algo so I can't do this my self currently

**Comment by Noctem** [comment]
Are the nearby locations precise enough for that? I know that they provide a PokéStop ID, but I didn't think that was a guarantee that they would be within 70 meters of it. Do we know what the maximum distance a nearby_pokemon could be from the listed PokéStop?

**Comment by Asner** [comment]
You should assign the pokemon to the spawnpoint to disappear in the next 15 minutes (if that pokestop have nearby spawnpoints). On an experiment i did in PGM looked like this:

<img width="484" alt="spawn" src="https://cloud.githubusercontent.com/assets/1508002/21365921/bca0e82e-c6b4-11e6-8daf-e1be6f6502e9.png">

**Comment by evenly-epic-mule** [comment]
@Noctem well not really, usually yes but not it's not sure
I the best system there would be to add unscanned spawnpoint near the pokestop until it has been found

on the other side there are nearby Pokemon without a pokestop_id, which would mean you could only set up the priority for scanning in that cell

**Comment by Noctem** [comment]
I can't think of a way to do this that would not be complex, computationally expensive, and/or occupy too much of workers' time. Occupying workers with a chase for Pokémon at unknown locations could ultimately prevent them from just visiting points in the regular rotation where they would hopefully be finding the rare ones anyways. So I'm closing this until I learn of a simple and fast implementation that would be worthwhile.
