### ISSUE TITLE
Workers clustering too much still

### ISSUE THREAD

**Issue by kbtbc** [Noctem/Monocle#57]
Still have an issue where workers overly concentrate in one or two areas of the map: 

http://i.imgur.com/Vhs7eKc.jpg

different area, same issue
http://i.imgur.com/sHsDZib.png

**Comment by m3g4mInD** [comment]
@kbtbc Too mutch workers delect 20%of your accts and restart scan

**Comment by Noctem** [comment]
What are your `GIVE_UP_KNOWN`, `GIVE_UP_UNKNOWN`, and `SKIP_SPAWN` config values? Raising them may help.

And what is your *skipped* count (in the terminal output) usually? 0? A small fraction of the number of visits? More skips than visits?

**Comment by kbtbc** [comment]
GIVE_UP_KNOWN = 75
GIVE_UP_UNKNOWN = 60
SKIP_SPAWN = 90     

It sometimes get's extreme. http://i.imgur.com/jKZlPrg.png

When I first start after -bootstrap for several hours the skip is zero.   Of the course of a couple of days (?) it appears that the skip has doubled the finds and then some.
