### ISSUE TITLE
Pokemons not showing up.

### ISSUE THREAD

**Issue by adishorvs** [Noctem/Monocle#59]
I ran python3 scan.py and python3 web.py -H 0.0.0.0 -P 80
![image](https://cloud.githubusercontent.com/assets/19682411/22292616/2e0fecb0-e31d-11e6-8d90-3fffe65b54ff.png)

I can't see any pokemons on the map. 
Pokemon found count (10s interval):
42 42 44 49 49 54 57 57 66 66

**Comment by steffenkopa** [comment]
Give it some time.

**Comment by adishorvs** [comment]
will do, thanks

**Comment by baskettcase** [comment]
Make sure and look at your scan log after awhile also. There was a SQL error for me so no Pokémon showed up no matter how long I ran it. Since then the problem has been fixed but still a good idea to keep your eye on the log file.

**Comment by m3g4mInD** [comment]
@baskettcase try to use mysql .Or show us your error.

**Comment by baskettcase** [comment]
I was using MySQL and the problem was fixed in the last push, so all is good for me.

**Comment by adishorvs** [comment]
started working for me, I need more workers and 2 captcha :)

**Comment by evenly-epic-mule** [comment]
The Map currently only shows pokemon with known spawn time
