### ISSUE TITLE
[Feature Request] List of Planned Features

### ISSUE THREAD

**Issue by cheezy64** [Noctem/Monocle#61]
Not really an issue, but this seems to be the easiest way to communicate with you.
I think there are many devs (including me) that would like to contribute, but there isn't a clear vision or path.  What are some features or annoyances that you'd like to be addressed?  I'd like to get some experience under my belt while contributing to this project

**Comment by Noctem** [comment]
Great! Help is helpful. [Here are a few things](https://github.com/Noctem/Monocle/wiki/To-Do-List) that I'd like done, I'll update that list as I think of more things (and as they're completed).

And feel free to [join us on Discord](https://discord.gg/RVuXKyg) if you haven't already.
