### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by ibuckshot5** [Noctem/Monocle#68]
I'm trying to run web.py. However, I keep getting this error:

```
OSError: [WinError 10013] An attempt was made to access a socket in a way forbid
den by its access permissions
```

I'm not sure if this is a system problem, or a Monocle problem. Any help?

EDIT: Here is the code i'm using:

`python web.py -H 127.0.0.1 -P 5000`

**Comment by thordurk91** [comment]
Are you trying to bind it to a port? or just runnin `py -3 web.py`?

**Comment by ibuckshot5** [comment]
I edited the post to include my command, so you can check that for problems.

**Comment by thordurk91** [comment]
That should be the same as default web.py does, this is something to do with your OS and a conflict on the port/socket.

**Comment by ibuckshot5** [comment]
Nevermind, I put it on a different port, and it worked.

**Comment by sunilbainsla** [comment]
It was happening for me because Pycharam is already using the default port 5000. While running the flask app I added different port like flask run -p 9999 and it worked for me
