### ISSUE TITLE
installing Pycairo

### ISSUE THREAD

**Issue by cyanosis78** [Noctem/Monocle#72]
pycairo wont install. I keep getting error message "could not find version that satisfies requirement pycairo (from version: ) no matching distribution for pycairo"

**Comment by Noctem** [comment]
They're not on PyPI. What operating system are you on?

## macOS
You can use [homebrew](http://brew.sh/) (or similar package managers):
```bash
brew install py3cairo
```
## Linux
Use your system's package manager.
### Arch
```bash
pacman -S python-cairo
```
### Fedora
```bash
dnf install python3-cairo
```
### Debian/Ubuntu/Mint/etc.
```bash
apt-get install python3-cairo
```
## Windows
You can install [one of these](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo) (*cp35* or *cp36*, depending on which version of Python you have).

**Comment by cyanosis78** [comment]
We got it to work through .whl
