### ISSUE TITLE
Clarification: Proxies

### ISSUE THREAD

**Issue by xenoguy** [Noctem/Monocle#76]
After running monocle for a few days, I've found that I can run about 3 accounts per public ip address without getting captchas.

If I configure a bunch of socks proxies in the config file, will it spread the workers out evenly among them?

**Comment by Noctem** [comment]
It will.

And are you using the hashing server? You should be able to use may more than 3 per IP without CAPTCHA issues if you're using hashes from allowed versions.

**Comment by xenoguy** [comment]
I bought a key for bosslands hash server and set it in the config file, but it doesn't stop or even seem to slow captcha rates.

**Comment by Noctem** [comment]
Set
```python
SPIN_POKESTOPS = True
```
in your config.

**Comment by xenoguy** [comment]
thanks!  this actually seems to have fixed the captcha issue.
