### ISSUE TITLE
Status Display in CLi

### ISSUE THREAD

**Issue by stunnaspinz** [Noctem/Monocle#77]
Looking at the wiki and seeing the list of status outputs for actions, operations and exceptions is perfect. Is there any way to get the complete listing? for example S and Q are not listed but seen often.

Running on windows 12 R2 (if this is needed.)
python --version = Python 3.6.0
pip3 --version = pip 9.0.1

**Comment by LabSen** [comment]
i had sometimes many "S"

Running on Ubuntu 16.10
python3.6 --version = Python 3.6.0
python3.6 -m pip --version = pip 9.0.1

**Comment by thordurk91** [comment]
S is when monocle is wwapping the account for a new one from the account queue.

most often due to 4 empty scans.

**Comment by stunnaspinz** [comment]
@thordurk91 is it common for this to get stuck in process for long periods of time? I have minimum 40 extra accounts for swapping purposes. While I have to admit I have not had this happen in the past 24 hours, It was something that happened quite often and did not appear to actually swap the accounts.

**Comment by thordurk91** [comment]
Only times I've seen it get stuck was when all my spare accounts were
banned or on a hashing timeput error that i dont get anymore

**Comment by stunnaspinz** [comment]
Yea.. I have not gotten it anymore I think since last pull. I have made 4 separate instances and they are all running just fine. 

What about the Q status any idea what that one was? (I was thinking quit but could not find anything in the code to reference it).

**Comment by Noctem** [comment]
`Q` means you exceeded your hashing quota.
