### ISSUE TITLE
Feature Request (hiding certain Pokemon) 

### ISSUE THREAD

**Issue by stunnaspinz** [Noctem/Monocle#80]
Feature request. Some kind of filtering. To hide items (and un-hide them) while live mapping. not using the trash_ids but in conjunction with that as well. My map is kinda cluttered and I'm not savvy in coding enough to work that out.

To remove the need to edit config, stop and start scan.py. could possibly integrate into the database somehow (I'm using MySQL)

**Comment by evenly-epic-mule** [comment]
I don't quite get what you are looking for but this may be it:
https://github.com/BassieWouters2/PokeMiner-PGM-Standalone-Frontend

**Comment by stunnaspinz** [comment]
Something like that yes but the one you linked is using the rocketmap frontend. which is a little bulky for what I was thinking.
