### ISSUE TITLE
Notification settings & Telegram iOS

### ISSUE THREAD

**Issue by eq2kazial** [Noctem/Monocle#83]
Hello,

Firstly I want to say thank you to Noctem and the other devs working on this project, it's been great so far.

I was wanting to know what settings I need to put in config.py to only get notifications for Pokémon that have over 90% IV's? I've changed the settings and put Ignore_Rarity = True but I'm still getting notifications of Pokémon like Arbok and Sandlash with low IV's. I've included my current config settings below.

Also, is it possible to change the notifications being sent to Telegram? With their iOS app all notifications say "Bot sent a map to the group XX". It'd be great if it said "A Pikachu 48.89% (8/4/10) has appeared!" instead. Also including the specific IV's on the web map next to the percentage would be nice. I've tried messing around with the code but I'm not too good with it.

Thanks in advance!

```
### OPTIONS BELOW THIS POINT ARE ONLY NECESSARY FOR NOTIFICATIONS ###
NOTIFY = True  # enable notifications

# create images with Pokémon stats for Tweets
# requires cairo and ENCOUNTER = 'notifying' or 'all'
TWEET_IMAGES = True

# As many hashtags as can fit will be included in your tweets, these will
# be combined with landmark-specific hashtags (if applicable).
HASHTAGS = {AREA_NAME, 'Monocle', 'PokemonGO'}
#TZ_OFFSET = 0  # UTC offset in hours (if different from system time)

# the required number of seconds remaining to notify about a Pokémon
TIME_REQUIRED = 300  # 5 minutes

### Only set either the NOTIFY_RANKING or NOTIFY_IDS, not both!
# The (x) rarest Pokémon will be eligible for notification. Whether a
# notification is sent or not depends on its score, as explained below.
NOTIFY_RANKING = 90

# Pokémon to potentially notify about, in order of preference.
# The first in the list will have a rarity score of 1, the last will be 0.
#NOTIFY_IDS = (130, 89, 131, 3, 9, 134, 62, 94, 91, 87, 71, 45, 85, 114, 80, 6)

# Sightings of the top (x) will always be notified about, even if below TIME_REQUIRED
# (ignored if using NOTIFY_IDS instead of NOTIFY_RANKING)
ALWAYS_NOTIFY = 14

# Always notify about the following Pokémon even if their time remaining or scores are not high enough
ALWAYS_NOTIFY_IDS = {25, 89, 108, 113, 115, 122, 130, 131, 132, 137, 143, 144, 145, 146, 147, 148, 149, 150, 151}

# Never notify about the following Pokémon, even if they would otherwise be eligible
#NEVER_NOTIFY_IDS = 	{20, 24, 28}	# Can also use TRASH_IDS

# Override the rarity score for particular Pokémon
# format is: {pokemon_id: rarity_score}
#RARITY_OVERRIDE = {148: 0.6, 149: 0.9}

# Ignore IV score and only base decision on rarity score (default if IVs not known)
#IGNORE_IVS = False

# Ignore rarity score and only base decision on IV score
IGNORE_RARITY = True

# The Pokémon score required to notify goes on a sliding scale from INITIAL_SCORE
# to MINIMUM_SCORE over the course of FULL_TIME seconds following a notification
# Pokémon scores are an average of the Pokémon's rarity score and IV score (from 0 to 1)
# If NOTIFY_RANKING is 90, the 90th most common Pokémon will have a rarity of score 0, the rarest will be 1.
# IV score is the IV sum divided by 45 (perfect IVs).
FULL_TIME = 1800  # 30 minutes, the number of seconds after a notification when only MINIMUM_SCORE will be required
INITIAL_SCORE = 0.9 # the required score immediately after a notification
MINIMUM_SCORE = 0.82  # the required score after FULL_TIME seconds have passed

# the number of encounter_ids to retain for duplicate checking. Should be at
# least as high as the highest number of notifications you'd send in an hour.
NOTIFICATION_CACHE = 100
```

**Comment by SkinnySnorlax** [comment]
ALWAYS_NOTIFY_IDS = Pokémon you want to get notified no matter their IVs

NOTIFY_IDS = Pokémon you want to get notified if they have same or better score than INITIAL_SCORE

So toggle that last one on, and writte in all the Pokémon numbers you want to get notifications of when they have >90% IVs

I would also like to know how to change telegram bot notification settings :)

**Comment by eq2kazial** [comment]
Hey, thanks. The thing is I'd like to know when any pokemon has over 90% IV's. I have encounter = all for this. Do I really have to put all 145ish numbers in Notify_ID's?

**Comment by SkinnySnorlax** [comment]
Ah sorry, understood you only wanted certain Pokémon.

Well, I'm not sure how NOTIFY_RANKING works. My guess is that it gives you a notifiation of the Pokémon that got the best score in a period of time. So you might still get notification of crappy IV's if they are rare.

**Comment by Noctem** [comment]
@eq2kazial If you want to be notified for *all* Pokemon with IVs meeting your score requirement then you should change to this:
```python
NOTIFY_RANKING = None
ALWAYS_NOTIFY = None
NOTIFY_IDS = tuple(range(1,152))
```
But unless I missed something your current config shouldn't be notifying about Arboks or Sandslashes with IVs under 82% unless they're among the 14 rarest for your area (which seems unlikely).

**Comment by eq2kazial** [comment]
I'm guessing that because I just started using this yesterday it thinks Arbok/Sandslash and some others are rare. But those settings are exactly what I needed, they work great! Thank you!

And +1 who's interested in more notifications options in the future :)

**Comment by Noctem** [comment]
Glad I could help.
