### ISSUE TITLE
Captcha push notifications

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#86]
Not sure if this is the right place, or I should post it into requests, so sorry in advance for any inconvenience.

Would it be hard to implement captcha push notifications through Telegram or similar, to your phone with a link to solve it, just like when sending them to 2captcha?

Edit: with 2captcha, whenever an account gets a captcha, it is sent to 2captcha, solved, and the account resumes its activity.
Without 2captcha, I manually solve them through PokeSensor, but that account gets swapped and flagged as benching. Once all accounts have been swapped out and there is no more the scanner stops. How can I avoid that flagging? or how to make the scanner use again those accounts?

**Comment by Noctem** [comment]
Notifications would be possible; but that's not a high development priority for me because I almost never get CAPTCHAs.

You can solve CAPTCHAs manually with *solve_captchas.py*, which will automatically and instantly put them back into the account rotation. If you solve them through other means then you could put them back onto the `extra_queue` (like [*solve_captcha* does](https://github.com/Noctem/Monocle/blob/develop/solve_captchas.py#L143), or set `CAPTCHA` to `False` for each account in *accounts.pickle* between executions of *scan.py*.

**Comment by manolomanila** [comment]
@Noctem didn't realize how to use _solve_captchas.py_ until now. Thank you for the help!

**Comment by AvatarQAZ** [comment]
Curious to how you don't get CAPTCHA?  External hash?

**Comment by baskettcase** [comment]
I get a couple a day lately. And I would love to have a notification got captchas

**Comment by manolomanila** [comment]
@baskettcase wait what? I'm getting 7 captchas an hour with 4 acc in a 4000 square meters area. Please, mind sharing how you do it?

**Comment by baskettcase** [comment]
@manolomanila hmm.. the only thing that I can think of is to level them up a bit? Otherwise that's about all I've done and out of 70 or so, I get maybe one to two captchas a day.

**Comment by manolomanila** [comment]
Thank you @baskettcase ! @stunnaspinz pointed that out too, allowing pokestop spins to level them up. After a few hours it seems to start working (from 7 captchas/hour with 4 accounts to 4 c/h using 16 accounts!). I might try hashing through Bossland as @AvatarQAZ said if I can't bring it lower. Thank you guys!

**Comment by baskettcase** [comment]
I just assumed that you were using the hashing server.. you'll reduce a lot if you do that. Im surprised you can do anything without it heh

**Comment by vlacorte** [comment]
@baskettcase @manolomanila how did you setup the worker grid?

**Comment by manolomanila** [comment]
I'll give the hashing server a try then. Honestly, I had no idea about the API and all, kinda new to all this. Thanks!

@vlacorte depending on the area I'm scanning, in the config file, (2,2), (2,3), (4,4), etc, Nothing fancy... ;P

**Comment by vlacorte** [comment]
@manolomanila that's what I'm using as well but seen other people with (10, 12) grids and got curious! Thanks for replying

**Comment by AvatarQAZ** [comment]
I am running a 9x10.  For a 50 sq km area.  It is actually a bit overkill.  I see a lot of pooling.  Thinking of expanding the area into our conjoined town (with less spawn density though).  

Hashing server fixes all.  And you would be surprised how efficient Monocle is with its RPM.

**Comment by manolomanila** [comment]
Hashing server fixed it. 0 captchas in 8 hours compared to the 50+ that I might have gotten before, thanks all!
@AvatarQAZ if you have free bazooka bullets, who is gonna judge you for killing that fly with it? (apart from PETA)
