### ISSUE TITLE
Install failed. Egg_info??

### ISSUE THREAD

**Issue by clahs** [Noctem/Monocle#90]
Hi,

When I tryning to install with commando "pip install -r requirements.txt" I got the error:

Command "python setup.py egg_info" failed with error code 1 in c:\users\pokemo~1\appdata\local\temp\pip-build-3mjkl_\aiohttp\

I am installing it on Windows 10.

**Comment by Noctem** [comment]
This isn't enough information for me to know what went wrong, other than that aiohttp failed to install. Are you sure that your `pip` is for Python 3?

**Comment by clahs** [comment]
Found out, that Python 2.x was installed not 3.x :/

However, I have another problem now. This time is the Mysql plugin:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,3,9,'final',1) -D__version__=1.3.9 "-IC:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include" -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc_mysql.c /Fobuild\temp.win32-3.6\Release\_mysql.obj /Zl
    _mysql.c
    _mysql.c(29): fatal error C1083: Cannot open include file: 'my_config.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\POKEMO~1\\AppData\\Local\\Temp\\pip-build-g5axpnb1\\mysqlclient\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\POKEMO~1\AppData\Local\Temp\pip-2ujfuokj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\POKEMO~1\AppData\Local\Temp\pip-build-g5axpnb1\mysqlclient\

Any ideas??

**Comment by thordurk91** [comment]
@clahs pip install pymysql instead of mysqldb and just edit the so the config call for the mysql db as `DB_ENGINE = 'mysql+pymysql://yourmysqlinfohere`
