### ISSUE TITLE
Not working after pull

### ISSUE THREAD

**Issue by manolomanila** [Noctem/Monocle#95]
Ended up doing a clean install because I mixed some old and new files and cant make it work, I see no workers in the map and I am getting 0 visits. Any ideas on what could be happening?

Edit: I think I rescued my old Monocle folder and pulled but happens the same. The old version works tho, but the extra accounts seem to be flagged as captcha.

**Comment by manolomanila** [comment]
After pull I get this error:

>C:\Monocle\Monocle>py scan.py
Traceback (most recent call last):
  File "scan.py", line 130, in <module>
    from monocle.worker import Worker
  File "C:\Monocle\Monocle\monocle\worker.py", line 4, in <module>
    from pogo_async.utilities import get_cell_ids, HAVE_POGEO
ImportError: cannot import name 'HAVE_POGEO'

**Comment by stunnaspinz** [comment]
run pip3 install -r requirements.txt --upgrade.. It fixed that for me.

**Comment by manolomanila** [comment]
@stunnaspinz That resolved the problem, thank you!

**Comment by manolomanila** [comment]
Noticed this:

`ERROR][worker-4] Missing Pokemon data in encounter response.`
